### ISSUE TITLE
Adapt sandbox_acp into application module

### ISSUE THREAD

**Issue by jensbin** [avaloqcloud/application-oci-acp#1]
Hi @ravishAvq. @AvinashBodhe1,

Can you bring the
* https://github.com/avaloqlabs/sandbox/tree/main/acp
* https://github.com/avaloqlabs/sandbox/tree/main/acp_vm

Into this module and utilize the ``acf_resource_compute`` module.

**Comment by AvinashBodhe1** [comment]
Done
